### ISSUE TITLE
why Link component

### ISSUE THREAD

**Issue by acornejo** [nmn/yarr#4]
I found this when looking for an alternative for page.js.

Could you elaborate why using Link component is required for working with react.js? Is this true with page.js as well, why the difference?

**Comment by nmn** [comment]
There are a few reason for the Link component:
1) page.js uses it's own event system on top of React's event system. This increases memory usage, and can often be less reliable. (there were versions of React that sometime didn't bubble events up correctly)
2) By making a Link component, there is a single place to add some extra functionality, like fast-click on touch-screens and good accessibility.
3) Adding a Link component also helps reduce the size of the library as there was a considerable amount of code for event management in page.js

**Comment by acornejo** [comment]
Thanks for that detail explanation.

Everything you said makes perfect sense, closing this issue.
