### ISSUE TITLE
React 0.13 dependency

### ISSUE THREAD

**Issue by stiff** [nmn/yarr#5]
Hi, I'm getting the warning about unmet peer dependency, because using react@0.14.3, while yarr requires react@^0.12.2 || 0.13.x. Are there any plans on updating to current react versions?

**Comment by nmn** [comment]
I'll take a look, and if there's isn't too much code I need to change I'll add a new version.

(yarr.js has very little React specific code, so it should be fine.)

**Comment by stiff** [comment]
Thanks, it actually seems to be working as is, despite the warning.

**Comment by nmn** [comment]
Latest code on github fixes this issue, could you be kind enough to test that everything still works correctly.

**Comment by stiff** [comment]
When I reference dependency to github like this:
```    "yarr.js": "nmn/yarr"``` I get the `Module not found: Error: Cannot resolve module 'yarr.js'`.

``` npm list
─┬ yarr.js@2.0.0-beta.1 (git://github.com/nmn/yarr.git#efee356034d864fc79cf219cb7e2925de2e5fade)
  └── react-tappable@0.5.7
```

**Comment by igorsantos07** [comment]
the same happens here... I guess the project is dead as well? :mask:

**Comment by igorsantos07** [comment]
The given version does not contain the final compiled code. @nmn, please, release the final version! Or at least, provide us with a version that does not blocks React updates, as you're not going to maintain the project anymore, so we won't get stuck with old versions - as you said, there's little React code, right?

**Comment by nmn** [comment]
I originally only write the code here for NPM, so I'm guessing the github links may be broken, I'll get on it.

**Comment by nmn** [comment]
I've published the latest release on NPM with the `next` flag.

Try installing it with `npm install yarr.js@next`.

Everything should work fine. If you find any problems let me know, and I'll make it the latest release soon.

**Comment by nmn** [comment]
@stiff since the last version, master on github has flow types built-in. So a compile step is necessary. As a result, the github repo will no longer work as is. you will need to compile the code first. Therefore, I suggest you stick to NPM. The current master has been published.

**Comment by stiff** [comment]
Thanks a lot, seems to be working. But `import {Link} from 'yarr.js'` now fails because Link is a es6Module, not react class, think it should be updated in docs to be perfect.

**Comment by nmn** [comment]
@stiff Actually, that's a bug in the index.js file. I'll fix it and ping you in a bit. It's tricky to support ES6 and CommonJS at the same time.

**Comment by stiff** [comment]
Yeah, it's very sad that ES6 went it's own way breaking great ideas like AMD and CommonJS.

**Comment by nmn** [comment]
@stiff would you mind pulling down again and testing. It should work correctly now.

**Comment by stiff** [comment]
Now npm update yarr.js says it is invalid:
``` npm update yarr.js
- lodash@4.1.0 node_modules/argparse/node_modules/lodash
- minimatch@3.0.0 node_modules/eslint/node_modules/minimatch
- async@1.5.2 node_modules/handlebars/node_modules/async
sampleapp@0.0.1 /workspace/sampleapp
├── babel-core@6.4.5
├── jade@1.11.0
├── webpack@1.12.9
└── yarr.js@2.0.0-beta.2  invalid ```

and `<Link onClick="console.log">..</Link>` throws `Uncaught TypeError: Cannot read property 'onClick' of undefined`. Seems like props are not properly passed to underlying `<a>`.

**Comment by nmn** [comment]
That's weird. I'll look into it. Please make sure you have the peerDependencies installed.

**Comment by nmn** [comment]
@stiff quite sure it's fixed now. Try v2.0.0-beta.4

**Comment by nmn** [comment]
@stiff all good?

**Comment by stiff** [comment]
Yes, seems to be ok now. Sorry, forgot to report it in time. Thank you!
