### ISSUE TITLE
question - how do i route a portion of a page

### ISSUE THREAD

**Issue by vshesh** [nmn/yarr#7]
It looks like I have to re-render the entire page when using yarr.
Is there a way to have some cruft (eg, nav bar or something) and then route only what's inside that?

Of course, there are hacks, like passing props to yarr, or writing a closure like:

``` js
function renderComponent(elem) {
  return function callback() {
    ReactDOM.render(<Main > {elem}</Main>, document.getElementById('container'));
  }
} 
yarr('/', renderComponent(<Home />));
```

but I'm wondering if there is some officially accepted way I'm missing.

**Comment by nmn** [comment]
@vshesh You've got the right answer there. Yarr is purposely kept small and simple. If you find yourself needing a nested router you're better off with React-Router, Yarr is for simple use-cases.
